### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by chazanov** [plepe/overpass-frontend#5]
Hi Plepe
```
sudo -i
npm -g install overpass-frontend
```
gave me
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', '-g', 'i', 'overpass-frontend' ]
2 info using npm@6.8.0
3 info using node@v8.12.0
4 verbose npm-session b91ddeca6e6ab7e9
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/overpass-frontend 1182ms
8 silly pacote tag manifest for overpass-frontend@latest fetched in 1209ms
9 timing stage:loadCurrentTree Completed in 1277ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule overpass-frontend@2.3.0 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/browserify-shim 105ms
18 silly pacote range manifest for browserify-shim@^3.8.14 fetched in 132ms
19 silly resolveWithNewModule browserify-shim@3.8.14 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/lodash 151ms (from cache)
21 http fetch GET 304 https://registry.npmjs.org/event-emitter 156ms (from cache)
22 http fetch GET 304 https://registry.npmjs.org/async 162ms (from cache)
23 silly pacote range manifest for lodash@^4.17.5 fetched in 164ms
24 silly resolveWithNewModule lodash@4.17.11 checking installable status
25 silly pacote range manifest for event-emitter@^0.3.5 fetched in 174ms
26 silly resolveWithNewModule event-emitter@0.3.5 checking installable status
27 silly fetchPackageMetaData error for lokijs@git+https://github.com/techfort/LokiJS.git Error while executing:
27 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t https://github.com/techfort/LokiJS.git
27 silly fetchPackageMetaData
27 silly fetchPackageMetaData fatal: Kann nicht zum aktuellen Arbeitsverzeichnis zurückwechseln.: Keine Berechtigung
27 silly fetchPackageMetaData
27 silly fetchPackageMetaData exited with error code: 128
28 silly pacote range manifest for async@* fetched in 188ms
29 silly resolveWithNewModule async@2.6.2 checking installable status
30 http fetch GET 200 https://registry.npmjs.org/@turf%2funion 219ms
31 silly pacote range manifest for @turf/union@^6.0.0 fetched in 231ms
32 silly resolveWithNewModule @turf/union@6.0.3 checking installable status
33 http fetch GET 200 https://registry.npmjs.org/xmlhttprequest 42ms
34 http fetch GET 200 https://registry.npmjs.org/@turf%2fdifference 239ms
35 silly pacote range manifest for xmlhttprequest@* fetched in 49ms
36 silly resolveWithNewModule xmlhttprequest@1.8.0 checking installable status
37 silly pacote range manifest for @turf/difference@^6.0.0 fetched in 246ms
38 silly resolveWithNewModule @turf/difference@6.0.2 checking installable status
39 http fetch GET 200 https://registry.npmjs.org/@turf%2fbbox-clip 285ms
40 http fetch GET 200 https://registry.npmjs.org/@turf%2fintersect 285ms
41 silly pacote range manifest for @turf/bbox-clip@^6.0.0 fetched in 292ms
42 silly resolveWithNewModule @turf/bbox-clip@6.0.3 checking installable status
43 silly pacote range manifest for @turf/intersect@^6.0.0 fetched in 291ms
44 silly resolveWithNewModule @turf/intersect@6.1.3 checking installable status
45 http fetch GET 200 https://registry.npmjs.org/bzip2 775ms
46 silly pacote range manifest for bzip2@^0.1.1 fetched in 777ms
47 silly resolveWithNewModule bzip2@0.1.1 checking installable status
48 http fetch GET 200 https://registry.npmjs.org/boundingbox 815ms
49 silly pacote range manifest for boundingbox@^0.1.0 fetched in 817ms
50 silly resolveWithNewModule boundingbox@0.1.4 checking installable status
51 http fetch GET 304 https://registry.npmjs.org/osmtogeojson 781ms (from cache)
52 http fetch GET 200 https://registry.npmjs.org/strsearch2regexp 778ms
53 silly pacote range manifest for osmtogeojson@^3.0.0-beta.2 fetched in 789ms
54 silly resolveWithNewModule osmtogeojson@3.0.0-beta.3 checking installable status
55 silly pacote range manifest for strsearch2regexp@^0.1.0 fetched in 783ms
56 silly resolveWithNewModule strsearch2regexp@0.1.0 checking installable status
57 http fetch GET 200 https://registry.npmjs.org/weight-sort 907ms
58 silly pacote range manifest for weight-sort@* fetched in 912ms
59 silly resolveWithNewModule weight-sort@1.3.0 checking installable status
60 timing stage:rollbackFailedOptional Completed in 1ms
61 timing stage:runTopLevelLifecycles Completed in 2405ms
62 verbose stack Error: exited with error code: 128
62 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
62 verbose stack     at emitTwo (events.js:126:13)
62 verbose stack     at ChildProcess.emit (events.js:214:7)
62 verbose stack     at maybeClose (internal/child_process.js:915:16)
62 verbose stack     at Socket.stream.socket.on (internal/child_process.js:336:11)
62 verbose stack     at emitOne (events.js:116:13)
62 verbose stack     at Socket.emit (events.js:211:7)
62 verbose stack     at Pipe._handle.close [as _onclose] (net.js:561:12)
63 verbose cwd /root
64 verbose Linux 4.20.7-arch1-1-ARCH
65 verbose argv "/usr/bin/node" "/usr/bin/npm" "-g" "i" "overpass-frontend"
66 verbose node v8.12.0
67 verbose npm  v6.8.0
68 error Error while executing:
68 error /usr/bin/git ls-remote -h -t https://github.com/techfort/LokiJS.git
68 error
68 error fatal: Kann nicht zum aktuellen Arbeitsverzeichnis zurückwechseln.: Keine Berechtigung
68 error
68 error exited with error code: 128
69 verbose exit [ 1, true ]
```

while your competitor `query-overpass` can easily be installed ;)

**Comment by plepe** [comment]
Apparently you can't clone git repositories as root. I had the same problem with trying. Fortunately @techfort published a new version of LokiJS recently which already includes my changes, so I could update the package to include the npm version of LokiJS.

Try again!

Anyway, why do you want to install overpass-frontend globally?

**Comment by plepe** [comment]
I think `query-overpass` is very limited in comparison. `overpass-frontend` can cache data locally (not in local-storage or such, but in the memory) and apply the queries on its cached data. It includes a minimalistic overpass server in itself (that's why it needs LokiJS). Also, if you do a query on a region, it will return already cached data right away and request only objects it doesn't know yet ...
